version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: contactsdb
      POSTGRES_USER: esther
      POSTGRES_PASSWORD: mypassword123
  server:
    build:
      context: .
    image: server:test
    depends_on:
      - db
    ports:
      - '8080:8080'
  client:
    build:
      context: ./client
    image: client:test
    volumes: 
      - ./client/node_modules
    depends_on: 
      - server
    ports:
      - '3000:3000'
    command: npm start